/* Automatically generated by './build/bin/build-entry.js' //*/

import button from "../packages/button/index.js";

const components = [
  button, 
];

const install = function (Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach((component) => {
    Vue.use(component);
  });

  Vue.prototype.$ELEMENT = {
    size: opts.size || "small",
    zIndex: opts.zIndex || 2000,
  };
};

if (typeof window !== "undefined" && window.Vue) {
  install(window.Vue);
}

export default {
  version: "1.0.0-alpha.14",
  locale: locale.use,
  i18n: locale.i18n,
  install,
  button
};
